#!/bin/bash

# Check to see if we want to clear out files
echo -n "Do you want to remove nohup.out [y/N]?"
read answer
if [ "$answer" == "y" ]; then
	rm nohup.out
fi
echo -n "Do you want to remove level.out [n/N]?"
read answer
if [ "$answer" == "y" ]; then
	rm level.out
fi
echo -n "Do you want to remove temp.out [n/N]?"
read answer
if [ "$answer" == "y" ]; then
	rm temp.out
fi

# Need this for reading the temp sensor
sudo pigpiod

# Start motion
nohup sudo motion &

# This is the temp sensor tester
nohup sudo python AM2302_test.py &

# This is the light sensor tester
nohup sudo python light_sensor.py &
