#!/bin/bash

# Give me time to stop the autostart if I'm having issues
# Just log in and remove the cron.flag file and it won't start
sleep 120

if [ ! -f /home/weather/weather/test/cron.flag ]; then
	echo "Flag removed - exit script without starting services"
	exit
fi

# Need this for reading the temp sensor
sudo pigpiod

# Start motion
sudo motion &

# This is the temp sensor tester
sudo python AM2302_test.py &

# This is the light sensor tester
sudo python light_sensor.py &
