#!/bin/bash

# Check to see if process exists
#go_pi=$(ps -ef | grep g[o])

# IP address for garagePi (and port) for messages
garagePi="192.168.0.215:5000"
HOME_DIR="/home/weather"

# Check to see if we stop , this is in case we just need to stop restarting
# You can just log in and touch stop, remove stop to keep going
if [ "$1" != "skipcheck" ]; then
    if [ -f ${HOME_DIR}/stop ]; then
        echo "$(date): Stopping go... file stop exists"
        exit 0
    fi
fi

# Put in a little delay before we start, gives us time to shut things down if
# we are getting repeated reboots
echo "$(date): Starting up ... going to sleep for 30 seconds"
sleep 30

# Starting up weather if it's not a crontab reboot
if [ -f /home/weather/weather/cronboot ]; then
    echo "Not sending text, removing cronboot"
    rm /home/weather/weather/cronboot
else
    echo "$(date): Sending text regarding reboot"
    wget --quiet --delete --no-check -t 1 "https://${garagePi}/send_message?msg=Starting weatherPi" 
fi

# Start up readings
# Loop through in case we get an error
echo "$(date): Starting to get readings"
fail_count=0
while :
do

    sudo  /home/weather/weather/weather_readings.py -d
    ((fail_count++))
    /home/weather/weather/util/event_times.py add_event weather_fail_counter 
    if [ -f /home/weather/weather/cronboot ]; then
        echo "Not sending text because cronboot exists, in fail loop, not deleting cronboot"
    else
        msg="Error in weather app. Fail count = ${fail_count} Restarting app at $(date)"
        wget --quiet --delete --no-check -t 1 "https://${garagePi}/send_message?msg=${msg}"
    fi
    if [ ${fail_count} -eq 5 ]; then
        echo "$(date): Error in weather. Failed 5 times ... rebooting weatherPi"
        echo "$(date): What is running?"
        /home/weather/weather/findpids
        sleep 60
        sudo reboot
    else
        echo "$(date): Error in weather. Restarting weather. fail_count = ${fail_count}"
        echo "$(date): Restart pigpiod"
        # We restart pigpiod because otherwise you leave open resources
        sudo service pigpiod restart
    fi
    sleep 5
done
