#!/bin/sh
### BEGIN INIT INFO
# Provides:          pigpiod
# Required-Start:    
# Required-Stop:
# Default-Start:     S
# Default-Stop:
# X-Interactive:
# Description: pigpio daemon to control GPIO pins on Raspberry Pi
# Short-Description:    GPIO controller
### END INIT INFO

PATH='/sbin:/bin:/usr/bin'

NAME=pigpiod
PIGPIOD=/usr/local/bin/pigpiod
PID_FILE=/var/run/pigpio.pid

RET=0

. /lib/lsb/init-functions

kill_pid () {
    if [ -f $PID_FILE ]; then
        kill $(cat ${PID_FILE})
        rm ${PID_FILE}
    fi
}

case "$1" in
    start|reload|restart|force-reload)
    	kill_pid
	log_daemon_msg "Starting pigpiod" "pigpiod"
	echo
    	$PIGPIOD
    	RET=$?
        ;;
    stop)
    	kill_pid
    	RET=$?
        ;;
    status)
        ;;
    *)
    	log_failure_msg "Usage: /etc/init.d/$NAME {start|stop|restart}"
    	RET=1
        ;;
esac

exit $RET

:
